name: Build and Release

concurrency:
  group: "build"
  cancel-in-progress: false

on:
    push:
        paths-ignore:
            - gradle.properties
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - run: chmod +x gradlew

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build
              run: ./gradlew build -Pcommit=${{ github.sha }} -Pbuild_number=${{ github.run_number }}

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.3.3
              with:
                  path: build/libs/*.jar

            - name: Get current branch
              id: branch
              run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | sed 's/_.*//')"

            - name: Create or update release
              id: create_release
              uses: softprops/action-gh-release@v2.0.4
              if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip release]')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: build/libs/*.jar
                  tag_name: ${{ steps.branch.outputs.branch }}
                  name: Release ${{ steps.branch.outputs.branch }}
                  draft: false
                  fail_on_unmatched_files: true
                  generate_release_notes: true
                  append_body: false
                  prerelease: false
                  make_latest: true
