name: Build and Release

on:
    push:
        paths-ignore:
            - gradle.properties
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Increment build number
              id: increment
              run: |
                  # Extract mod_version from gradle.properties
                  version=$(grep "^mod_version" gradle.properties | cut -d'=' -f2)
                  base_version=$(echo "$version" | cut -d'-' -f1)
                  build_number=$(echo "$version" | grep -oP '\-\K\d+')

                  new_build_number=$((build_number + 1))
                  new_version="${base_version}-${new_build_number}"

                  sed -i "s/^mod_version=.*/mod_version=${new_version}/" gradle.properties
                  echo "Updated mod_version to ${new_version}"
                  
                  echo "new_build_number=${new_build_number}" >> $GITHUB_OUTPUT

            - name: Commit changes
              run: |
                git config --local user.name "GitHub Actions"
                git config --local user.email "actions@github.com"
                git add gradle.properties

                commit_message="Increment build number to ${{ steps.increment.outputs.new_build_number }}"
                echo "$commit_message"

                git commit -m "$commit_message"
                git push origin HEAD
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: chmod +x gradlew

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3.3.2

            - name: Build with Gradle Wrapper
              run: ./gradlew build

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.3.3
              with:
                  path: build/libs/*.jar

            - name: Get current branch
              id: branch
              run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | sed 's/_.*//')"

            - name: Create or update release
              id: create_release
              uses: softprops/action-gh-release@v2.0.4
              if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip release]')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: build/libs/*.jar
                  tag_name: ${{ steps.branch.outputs.branch }}
                  name: Release ${{ steps.branch.outputs.branch }}
                  draft: false
                  fail_on_unmatched_files: true
                  generate_release_notes: true
                  append_body: false
                  prerelease: false
                  make_latest: true
